#ifndef PSEUDO_POWER_SPECTRUM_PSEUDO_POWER_SPECTRUM_HPP
#define PSEUDO_POWER_SPECTRUM_PSEUDO_POWER_SPECTRUM_HPP


#include <cmath>
#include <iostream>

#include <Eigen/Core>

#endif //PSEUDO_POWER_SPECTRUM_PSEUDO_POWER_SPECTRUM_HPP
